/// Flutter icons FlutterIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcon
///      fonts:
///       - asset: fonts/FlutterIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlutterIcon {
  FlutterIcon._();

  static const _kFontFam = 'FlutterIcon';

  static const IconData kaaba = const IconData(0xe800, fontFamily: _kFontFam);
}
